### ISSUE TITLE
Vyčítání čvercové matice z vysokorychlostní celooblohové kamery

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/CRREAT_cars#9]
V prvním nastavení celooblohová kamera nemá nastavenou čtvercovou matici a používá preset 1024x768

![image](https://user-images.githubusercontent.com/1194177/124024848-0b4e6e80-d9f0-11eb-9eca-460e8bcb9742.png)

Nevýhodou tohoto nastavení je, že ukládá i data mimo zorné pole celooblohového snímku. Tj. prodlužuje čas uložení.

**Comment by kaklik** [comment]
Ve webovém rozhraní je však možné nastavit i čtvercové rozlišení 768x768 nebo 1024x1024. 

![image](https://user-images.githubusercontent.com/1194177/124026084-86fceb00-d9f1-11eb-9b29-2e9e302fe55b.png)

Jen je potřeba po změně rozlišení spustit "black calibration" při zatemněné koupuli, aby se normalizovalo zesílení jednotlivých buněk na čipu. 

Nové nastavení je potřeba otestovat @kakl

**Comment by kaklik** [comment]
Vyčítání čvercového pole z kamery funguje.  Jako nejlepší rozlišení se zatím jeví čtverec 928x928 pixelů. 

https://www.youtube.com/watch?v=By5Gty5SoZU

**Comment by kakl** [comment]
Neni mi uplne jasne, jaka rozliseni jsou povolena, nicmene cip neni uplne uprostred objektrivu. Pro rozliseni 928 x 928 lze nastavit offset 176 x 66.

**Comment by kakl** [comment]
![image](https://user-images.githubusercontent.com/6756980/125328278-70855680-e344-11eb-8abe-c1b0af92f8b9.png)

**Comment by kaklik** [comment]
> Neni mi uplne jasne, jaka rozliseni jsou povolena, nicmene cip neni uplne uprostred objektrivu. Pro rozliseni 928 x 928 lze nastavit offset 176 x 66.

Ano, na záležitost že čip není přesně v ose objektivu jsem taky narazil. Považoval jsem to ale za zanedbatelný problém. Zkusím, jestli stejný offset platí i pro můj případ. 

Co se týká rozlišení, tak možnosti jsou popsány v [tomhle dokumentu](https://www.krontech.ca/wp-content/uploads/2019/03/Chronos-1.4-Beta-0.3.0-User-Manual-r1.pdf). Konkrétně:

![image](https://user-images.githubusercontent.com/1194177/125330104-9ad81380-e346-11eb-9ed2-7d84166c4610.png)
